# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('feedback_text', models.TextField()),
                ('submitter_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
